# Change these first
owner: amsterdam
repo: ee-upptime

sites:
  # - name: Developers Amsterdam
  #   url: $SITE_DEVELOPERS_AMSTERDAM
  # - name: Data Amsterdam
  #   url: $DATA_AMSTERDAM
  # - name: Bomen Amterdam
  #   url: $BOMEN_AMSTERDAM
  # - name: Omslag route Amsterdam
  #   url: $OMSLAG_ROUTE
  # - name: Amsterdam Maps
  #   url: $MAPS_AMSTERDAM
  # - name: Meldingen Amsterdam
  #   url: $MELDINGEN_URL
  # - name: Amsterdam Design System
  #   url: $AMSTERDAM_DESIGN_SYSTEM
  - name: Mijn Amsterdam
    url: https://mijn.amsterdam.nl
    method: HEAD
    expectStatus: 200
    options:
      insecure: true
  # - name: Amsterdam Sensoren
  #   url: $SENSOREN_AMSTERDAM
  # - name: Amsterdam Open Stad
  #   url: $OPEN_STAD
  # - name: Amsterdam Hior
  #   url: $HIOR_AMSTERDAM
  # - name: Bereikbaarheid Amsterdam
  #   url: $BEREIKBAARHIED_AMSTERDAM


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /ee-upptime
  logoUrl: https://api.data.amsterdam.nl/api/gemeente_Amsterdam_logo.svg
  name: Amsterdam Uptime
  introTitle: "Uptime status pagina voor Gemeente Amsterdam applicaties"
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 */2 * * *"
  responseTime: "0 */2 * * *"
  staticSite: "0 */12 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"