name: SSL Test in GitHub Actions

on:
  push:
  workflow_dispatch:

jobs:
  ssl-check:
    runs-on: ubuntu-latest
    steps:
      - name: Download DigiCert CA certificate
        run: |
          mkdir -p /etc/ssl/certs
          curl -o /etc/ssl/certs/DigiCertCA.crt https://dl.cacerts.digicert.com/DigiCertG2TLSEURSA4096SHA3842022CA1.crt
      - name: Test SSL with curl from GitHub Actions
        run: |
          curl -vI --cacert /etc/ssl/certs/DigiCertCA.crt https://mijn.amsterdam.nl || echo "Connection failed"
