name: SSL Test in GitHub Actions

on:
  push:
  workflow_dispatch:

jobs:
  ssl-check:
    runs-on: ubuntu-latest
    steps:
      - name: SSL controle met curl
        run: |
          URL="https://mijn.amsterdam.nl"
          echo "Controleer SSL-status voor $URL..."

          response=$(curl -vI --silent $URL 2>&1)

          echo "$response"

          if echo "$response" | grep -q "SSL certificate problem"; then
              echo "SSL-certificaatfout: unable to get local issuer certificate"
              exit 1
          else
              echo "Geen SSL-certificaatfout gedetecteerd"
          fi
