name: SSL Test in GitHub Actions

on:
  push:
  workflow_dispatch:

jobs:
  ssl-check:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSL with curl from GitHub Actions
        run: |
          curl -vI https://mijn.amsterdam.nl || echo "Connection failed"
