name: SSL Test in GitHub Actions

on:
  push:
  workflow_dispatch:

jobs:
  ssl-check:
    runs-on: ubuntu-latest
    steps:
      - name: Create local cert directory
        run: mkdir -p ./certs

      - name: Download DigiCert CA certificate in PEM format
        run: |
          curl -o ./certs/DigiCertCA.pem https://www.digicert.com/CACerts/DigiCertG2TLSEURSA4096SHA3842022CA1.pem

      - name: Test SSL with curl from GitHub Actions
        run: |
          curl -vI --cacert ./certs/DigiCertCA.pem https://mijn.amsterdam.nl || echo "Connection failed"
